# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

notifications:
  email: false

sudo: false

language: node_js

node_js:
  - '5.4.1'

env:
  global:
    - GH_REF: 'UPDATE_WITH_GH_REF'
    - secure: 'UPDATE_WITH_GH_TOKEN'

before_script:
  - 'npm install -g gulp'

before_install:
  - 'npm i'

script:
  - 'npm test'

after_success:
  - 'npm run-script coverage'

before_deploy:
  - 'npm run-script build'

deploy:
  provider: npm
  skip_cleanup: true
  email: 'UPDATE_WITH_NPM_DEPLOY_EMAIL'
  api_key:
    secure: 'UPDATE_WITH_NPM_DEPLOY_SECRET'
  on:
    tags: true
    repo: 'inveniosoftware/invenio-files-js'
    branch: master
    node: '5.4.1'

after_deploy:
  - ./deploy.sh
